id: I2EBE222F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T14:03:54+00:00'
last_modified: '2022-06-07T16:41:47.280145+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30121
  title: རྒྱལ་བ་རྡོ་རྗེ་འཆང་ཡབ་ཡུམ་གྱི་རྣམ་ཐར་རིན་ཆེན་གཏེར་མཛོད་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6ED9:
      image_group_id: I1KG9619
      title: ''
      total_pages: 544
      order: 1
      base_file: 6ED9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
