id: P002974
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:31:58.874359
source_metadata:
  id: bdr:W30121
  title: རྒྱལ་བ་རྡོ་རྗེ་འཆང་ཡབ་ཡུམ་གྱི་རྣམ་ཐར་རིན་ཆེན་གཏེར་མཛོད་སོགས།
  author: ''
  volumes:
    244b0dd54d6c4f628239b5a410f61841:
      image_group_id: I1KG9619
      title: ''
      volume_number: 1
      total_pages: 544
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
